server:
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bus_management?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mysql
  sql:
    init:
      schema-locations: classpath:sql/init_table.sql
      mode: never